### ISSUE TITLE
关于搭建项目环境缺少requirements.txt

### ISSUE THREAD

**Issue by huanglf714** [DengPingFan/SINet#11]
尊敬的作者您好：
在阅读了您的论文后，我想要搭建项目环境复现一下您的测试数据，但是在pip install -r requirements.txt这一步中，我在仓库里并没有找到requirements.txt这一文件，不知道您是否注意到并提供一下。感谢您的工作成果。

**Comment by GewelsJI** [comment]
I have uploaded the `requirement.txt`. Thank you for your attention.
