### ISSUE TITLE
Make my datesets for the code

### ISSUE THREAD

**Issue by qingHX** [DengPingFan/SINet#12]
I  am interested in  the paper and code.
I  want to  train the code on my  datesets,  but  I   don’t  know how  to  make the annotation, can  you give some  tools or ohter advises.  Thanks !!!!!!

**Comment by DengPingFan** [comment]
> I am interested in the paper and code.
> I want to train the code on my datesets, but I don’t know how to make the annotation, can you give some tools or ohter advises. Thanks !!!!!!

Hi, you can send me an email (dengpfan@gmail.com) and your wechat so that we can contact real-time.
