### ISSUE TITLE
training setting (iv)

### ISSUE THREAD

**Issue by cxzhou95** [DengPingFan/SINet#13]
Hi,

In Table 3, there are three training settings for SINet, and you mention that the baseline models are trained using the training setting (iv), but I cannot find any description about this setting in the paper. Is it because I miss something?

**Comment by DengPingFan** [comment]
> Hi,
> 
> In Table 3, there are three training settings for SINet, and you mention that the baseline models are trained using the training setting (iv), but I cannot find any description about this setting in the paper. Is it because I miss something?

Sorry for this issue. Actually, the training set is (iii) CAMO + COD10K + EXTRA (CPD1k)
