### ISSUE TITLE
关于归一化

### ISSUE THREAD

**Issue by BrownSweater** [DengPingFan/SINet#14]
https://github.com/DengPingFan/SINet/blob/33e9eb3b9ef57ddc9dbe84d3fbae7acdae4abdb8/MyTest.py#L43

为什么要这样归一化？如果输入的预测图片是一个负样本，没有正响应值，这样归一化是否不合理？

**Comment by Patrickctyyx** [comment]
看 41 行，cam 经过 Sigmoid 处理过

**Comment by BrownSweater** [comment]
> 看 41 行，cam 经过 Sigmoid 处理过

是的，经过Sigmoid处理后已经得到了每一个像素点是否是正样本的概率值。如果输入的图片是负例，即图片中不存在伪装物体。那么输出值cam应该都是低响应值。如果再使用最大最小归一化，会将这些低响应值重新激活。我认为这样不太合理啊，是我还有什么没考虑到吗？

**Comment by DengPingFan** [comment]
> > 看 41 行，cam 经过 Sigmoid 处理过
> 
> 是的，经过Sigmoid处理后已经得到了每一个像素点是否是正样本的概率值。如果输入的图片是负例，即图片中不存在伪装物体。那么输出值cam应该都是低响应值。如果再使用最大最小归一化，会将这些低响应值重新激活。我认为这样不太合理啊，是我还有什么没考虑到吗？

目前训练的时候都用的正样本，你说的问题确实可能存在，我们目前没有加入负样本进行训练，负样本的标注代价是0。目前还么有人做，或者这个是你可以探索的一个新的贡献点。
