### ISSUE TITLE
MyTrain

### ISSUE THREAD

**Issue by TommyYangXP** [DengPingFan/SINet#16]
where is "MyTrian.py"??????

**Comment by DengPingFan** [comment]
> where is "MyTrian.py"??????

I will send you via Email, best.

**Comment by TommyYangXP** [comment]
> > where is "MyTrian.py"??????
> 
> I will send you via Email, best.

363063705@qq.com,thanks

**Comment by TommyYangXP** [comment]
By the way, I think the formula 4 in "4.2 Identification Module (IM)" of the paper,I think it should be rfkc2 = rfkc1 ⊗ Π k-1 j=0 Bconv(UP(fjc1)),or maybe I was wrong.

**Comment by DengPingFan** [comment]
> By the way, I think the formula 4 in "4.2 Identification Module (IM)" of the paper,I think it should be rfkc2 = rfkc1 ⊗ Π k-1 j=1 Bconv(UP(fjc1)),or maybe I was wrong.

Thank you for pointing out this typo, we will fix it accordingly.

**Comment by TommyYangXP** [comment]
> > By the way, I think the formula 4 in "4.2 Identification Module (IM)" of the paper,I think it should be rfkc2 = rfkc1 ⊗ Π k-1 j=1 Bconv(UP(fjc1)),or maybe I was wrong.
> 
> Thank you for pointing out this typo, we will fix it accordingly.
Ok,thanks
