### ISSUE TITLE
train.py文件

### ISSUE THREAD

**Issue by qiuyecv** [DengPingFan/SINet#17]
作者你好，你们给的是直接测试数据集，我想自己训练，你们有类似train.py文件吗

**Comment by DengPingFan** [comment]
> 作者你好，你们给的是直接测试数据集，我想自己训练，你们有类似train.py文件吗

The training code could be available via email (dengpfan@gmail.com). Please provide your Name & Institution.

Best,

**Comment by qiuyecv** [comment]
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DengPingFan"<notifications@github.com&gt;; 
发送时间: 2020年11月6日(星期五) 下午2:32
收件人: "DengPingFan/SINet"<SINet@noreply.github.com&gt;; 
抄送: "821232278"<821232278@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [DengPingFan/SINet] train.py文件 (#17)





  
作者你好，你们给的是直接测试数据集，我想自己训练，你们有类似train.py文件吗
  
The training code could be available via email (dengpfan@gmail.com). Please provide your Name &amp; Institution.
 
Best,
