### ISSUE TITLE
What tools did you use to display the statistics of COD10K dataset?

### ISSUE THREAD

**Issue by 17Skye17** [DengPingFan/SINet#19]
Hi,
Thank you for releasing the code, nice work.
I think Figure 4 in your paper is very nice, but I didn't find any tool to draw figures like Figure 4(a). Could you share the tools with us? : )

**Comment by DengPingFan** [comment]
Hi，there are some basic tools: https://vis.baidu.com/

**Comment by 17Skye17** [comment]
Thank you for sharing.

**Comment by aalihhiader9211** [comment]
Mentioned link is unreacheable

**Comment by 17Skye17** [comment]
> Mentioned link is unreachable

Hi, you can access:

https://echarts.apache.org/en/index.html
