### ISSUE TITLE
关于单通道训练的问题

### ISSUE THREAD

**Issue by HOWTYEE** [DengPingFan/SINet#21]
作者您好，我的训练集图像为单通道，而您的图像为三通道。我将预训练resnet的第一层已经改成了单通道输入，但是无法正确运行。我想请教一下如何更改以适应单通道分割？已经给您发邮件希望您提供train.py作参考。

**Comment by DengPingFan** [comment]
hi, 已经发送代码给你了。

祝好

HOWTYEE ***@***.***> 于2021年7月19日周一 下午1:06写道：
