### ISSUE TITLE
SINet.py question

### ISSUE THREAD

**Issue by FrankWuuu** [DengPingFan/SINet#22]
Hello doctor Deng, could you help me?
 In the paper, there is a Bconv1x1 after Concatenation C in the RF module. But in the SINet.py, the code you given is like this:         self.conv_cat = BasicConv2d(4*out_channel, out_channel, 3, padding=1), then the kernel size is 3. So I want to know if is there any problem here? Or just because I did not get the idea?

**Comment by DengPingFan** [comment]
You can just follow the code. Some small details did not mentioned in the paper. 

best,
