### ISSUE TITLE
Results of SINet are not available

### ISSUE THREAD

**Issue by clelouch** [DengPingFan/SINet#28]
Thanks for your code and paper. It seems that the link is expired.

**Comment by DengPingFan** [comment]
Hi, 

Which link? Could you provide this link? I will check it again. 

Best,

**Comment by clelouch** [comment]
![image](https://user-images.githubusercontent.com/33519394/142212398-ba18699d-148e-4310-83c7-e514ed8ad2c4.png)
Thank you for your prompt reply. 
The underlined one (3.1.1).

**Comment by DengPingFan** [comment]
Hi,
SINet results: https://drive.google.com/drive/folders/1uxIuT5havrkL07Skp_oQHoiJ8m2he1Fn
Other model results: https://drive.google.com/drive/folders/1jGE_6IzjGw1ExqxteJ0KZSkM4GaEVC4J

best,
