### ISSUE TITLE
Loss

### ISSUE THREAD

**Issue by jiangxinhao2020** [DengPingFan/SINet#30]
weit = 1+5*torch.abs(F.avg_pool2d(mask, kernel_size=31, stride=1, padding=15)-mask)
您好，您论文使用了F3Net的损失函数，请问kernel_size是否是超参数，31是如何选取的，能否选取51，15，9等数字。感谢解答！

**Comment by DengPingFan** [comment]
这个参数是继承了原始F3Net模型设定：https://github.com/weijun88/F3Net/blob/eecace3adf1e8946b571a4f4397681252f9dc1b8/src/train.py#L19

你可以根据不同情况选取其他大小
