### ISSUE TITLE
torch版本

### ISSUE THREAD

**Issue by liangjxiong** [DengPingFan/SINet#31]
您好！train的时候，pytorch版本是多少？

**Comment by GewelsJI** [comment]
torch>1.6即可，只要能够有apex支持功能就好了

**Comment by i-dont-know-how-to-sign-up** [comment]
你好！想请教一下，我看requirement里面torch版本是1.3.1，但实际运行的时候报了一个错，我查了一下是因为torch版本太旧，请问torch版本要升级吗

**Comment by GewelsJI** [comment]
应该能适配高版本torch，可以尝试一下
