### ISSUE TITLE
Object detection with just the bounding box

### ISSUE THREAD

**Issue by tanya-suri** [DengPingFan/SINet#33]
hello,
Can we perform the bounding box detection without segmentation mask using this code?,.

**Comment by GewelsJI** [comment]
Hi, @tanya-suri 

Sure. But you may modify the datatloader and loss function to fit with the task target of object detection, like [OSFormer: One-Stage Camouflaged Instance Segmentation with Transformers](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=kakwJ5QAAAAJ&cstart=20&pagesize=80&citation_for_view=kakwJ5QAAAAJ:ruyezt5ZtCIC) does.
