### ISSUE TITLE
复现了一下SINet的结果（Apex lib (mode=O1)，40epoch），我看复现结果差距不大，这样应该算复现成功吧？

### ISSUE THREAD

**Issue by ycyinchao** [DengPingFan/SINet#34]
![8FL81A(~%J_4 RVA3PH0A33](https://user-images.githubusercontent.com/105531816/185782884-47c3423f-540a-4b56-8fed-a6931f889e0d.png)
（红色框标注的是复现结果要更好一点点，没标注的说明要差点）
这样应该表示复现没有问题吧？（刚接触这个领域，不太清楚性能差距多大才算复现的不太好）

**Comment by GewelsJI** [comment]
根据你的结果来看，有0.00X的差距是正常的，有更多细节问题可以直接邮件（gepengai.ji@gmail.com）与我沟通
