### ISSUE TITLE
Bconv: conv + BN + relu, as follows. The definition of bconv means conv + BN + relu, but forward only uses conv + BN. I tested it a little, but it had little impact on the final result.

### ISSUE THREAD

**Issue by ycyinchao** [DengPingFan/SINet#35]
Bconv: conv + BN + relu, as follows. The definition of bconv means conv + BN + relu, but forward only uses conv + BN. I tested it a little, but it had little impact on the final result.
![image](https://user-images.githubusercontent.com/105531816/185797460-6db7af41-6c10-474d-ae55-b518feed533f.png)

**Comment by GewelsJI** [comment]
relu初始化后实际上并未使用，可以直接删除掉
