### ISSUE TITLE
SINET用于伪装目标检测

### ISSUE THREAD

**Issue by wangsun1996** [DengPingFan/SINet#36]
我想把这个网络用于伪装目标的检测，请问能否替代现有通用目标检测框架中的主干部分？作者有试过与通用框架的监测结果相比效果如何吗？
或者用SINET网络有别的方式能实现目标检测吗？

**Comment by WkangLiu** [comment]
这个网络不就是用于伪装目标检测的嘛？

**Comment by wangsun1996** [comment]
> 我看结果都是分割的结果

**Comment by WkangLiu** [comment]
我小白兄弟，这我就不清楚了，加油
