### ISSUE TITLE
关于论文的一些疑问

### ISSUE THREAD

**Issue by pengqianli** [DengPingFan/SINet#9]
尊敬的作者您好，
在读了您的工作以后，我有几点模糊的地方想请您明确一下：
1、您在github上给出的中/英文论文与cvf open Access上的论文在内容上有些微出入，例如，Sec.5.1删除了trainning set(i)CPD1K，Table3删除了CPD1K-Test的内容，可能还有其他地方我没有注意到。我的问题是，github上给出的版本是终版吗（我应该以这一版论文数据为准吗）？
2、您的数据集文中称收集了10000张数据，但是下载后发现trainning+testing set =4040+2026<10000？根据您论文中所述的COD10k的test set为2026张iamge，您给出的trainning set是否有缺漏？只对于COD10K来说，您的模型是在4040张数据上进行的训练还是在7974（=10000-2026）张数据上进行了训练？（如果是由于我个人漏读，我表示抱歉）
3、您最新版给出的论文中，trainning setting(iii)中，使用了CAMO + COD10K + EXTRA作为训练集，这个EXTRA是指什么？（CPD1K吗？），至于COD10K，同样有使用4040张还是7974张数据的疑问。
4、您的模型在使用imagenet预训练后，（在COD等训练集上进行训练之前）是否在SOD训练集上finetune过？
5、您更新了表格的内容并称40epoch后取得了更好的效果，那么，假如后续有新的工作需要跟您的模型进行对比，是cite您论文原论文中的数据还是您更新后的数据呢？

**Comment by pengqianli** [comment]
注：关于问题2，我在您的项目主页（http://dpfan.net/Camouflage/）上也没有发现有数据更新的通知。

**Comment by DengPingFan** [comment]
> 尊敬的作者您好，
> 在读了您的工作以后，我有几点模糊的地方想请您明确一下：
> 1、您在github上给出的中/英文论文与cvf open Access上的论文在内容上有些微出入，例如，Sec.5.1删除了trainning set(i)CPD1K，Table3删除了CPD1K-Test的内容，可能还有其他地方我没有注意到。我的问题是，github上给出的版本是终版吗（我应该以这一版论文数据为准吗）？
> 2、您的数据集文中称收集了10000张数据，但是下载后发现trainning+testing set =4040+2026<10000？根据您论文中所述的COD10k的test set为2026张iamge，您给出的trainning set是否有缺漏？只对于COD10K来说，您的模型是在4040张数据上进行的训练还是在7974（=10000-2026）张数据上进行了训练？（如果是由于我个人漏读，我表示抱歉）
> 3、您最新版给出的论文中，trainning setting(iii)中，使用了CAMO + COD10K + EXTRA作为训练集，这个EXTRA是指什么？（CPD1K吗？），至于COD10K，同样有使用4040张还是7974张数据的疑问。
> 4、您的模型在使用imagenet预训练后，（在COD等训练集上进行训练之前）是否在SOD训练集上finetune过？
> 5、您更新了表格的内容并称40epoch后取得了更好的效果，那么，假如后续有新的工作需要跟您的模型进行对比，是cite您论文原论文中的数据还是您更新后的数据呢？

hi，感谢您对我们的工作感兴趣
回答1. 论文以cvf open access为准。我们之所以去掉CPD1K是不希望用到检测伪装人(你懂得)的应用上。
回答2. 数据集是10K，我们训练SINet仅仅用了CAM部分的数据，Non-CAM大概有4000多张，我们近期会公布，也是因为问题1中涉及到的一些类别的问题。所以我们延迟公布。
回答3. 你下载的结果没有错。训练SINet模型是用的，CAMO + COD10K-training + CPD1k training set
回答4. EXTRA指的就是CPD1K training. 我们不希望推广到伪装人物。 因此仅仅用CAMO + COD10K-training其实也能得到很好的结果。
回答5.  cite CVPR 2020原文就可以了。SINet会和DeepLab的工作一样，持续更新，提供类似SINet V1, SINet V2, 高级版本。

最后感谢您的关注，进一步的问题，可以发邮件加我个人微信，实时交流。

祝好，

登平

**Comment by ycyinchao** [comment]
trainning+testing set =4040+2026=6066，但是COD10k 只有5,066 camouflaged，那么另外1k camouflaged全部来自于CPD1k training set？但我看回答3，训练集是来自于CAMO + COD10K-training + CPD1k training set。那么我是否可以理解如下：
1. COD10K训练集中包括了CAMO的训练集，共3040张，另外1000来自于CPD1k training set
2. 测试集2026张图片默认是全部来自于COD10K-test
3. COD10K：3000显著目标（background）；1934无伪装目标； COD10K-training 3040张；COD10K-test 2026张

**Comment by GewelsJI** [comment]
你好，CPD1K的训练设定已被迭代，更新后的训练集合仅仅包含了4040张样本（COD10K-Train部分和CAMO-Train部分），所有的模型已经重新训练过，也可以参考一下我们近期的两个工作：

**Comment by ycyinchao** [comment]
@GewelsJI 好的，我最近才开始看相关论文，还有个疑问：
![image](https://user-images.githubusercontent.com/105531816/185780626-47cca836-734e-421d-9cfd-a083454a8a76.png)
这个符号指的是adpEm？还是meanEm或maxEm？（Em指的是E-measure(Enhanced-alignment Measure)）

**Comment by GewelsJI** [comment]
@ycyinchao ，由于这个是二值评测指标，所以要根据不同阈值化方法来决定，具体你可以根据论文论述来看看属于哪一个

**Comment by ycyinchao** [comment]
@GewelsJI 
![image](https://user-images.githubusercontent.com/105531816/185780967-88bff615-a8c0-4a21-abf2-06c4a42789e9.png)
论文中相关论述部分只有这一点，我没有看出来具体是哪一种？一般情况下是什么？

**Comment by GewelsJI** [comment]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/38354957/185781519-07fa9449-1f0a-4d44-868e-78e003e65589.png">
一般会有注明，请参考原文说明即可

**Comment by ycyinchao** [comment]
多谢！我这就去看看
